Fix:검색목록 구현!!!!!
subscriptionRescueTeam/save-my-youth pull request #159
Opened 2022-05-20 08:53 UTC by kmin-jeong

### PR 타입(하나 이상의 PR 타입을 선택해주세요)

- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
ex) feat/login -> dev

### 변경 사항
console.log로만 나오던 검색 결과를 화면에 목록으로 뿌려준다

### 테스트 결과
![캡](https://user-images.githubusercontent.com/53456037/169492249-a70edbb4-c5fe-40eb-bd27-e2127a5bc5f5.jpg)
![캡1](https://user-images.githubusercontent.com/53456037/169492256-ba23319c-2522-42a7-b324-c3ec538505a3.jpg)

### Issue

resolved: #158

2022-05-20 08:56 UTC, jwun95 approved these changes

2022-05-20 11:12 UTC, Lela12 commented on frontend/src/components/SearchCardItem/index.tsx
> +    @media screen and (min-width: 500px) {
rem, em으로 넣어주시면 좋을 것 같아요!

2022-05-20 14:38 UTC, hotbreakb reviewed
좋아요 👍

2022-05-20 14:38 UTC, hotbreakb commented on frontend/src/components/SearchCardItem/index.tsx
> +    margin: 30px 30px 20px 10px;
`px`보다는 `rem`이나 `%` 쓰면 더 좋겠네요 👍

2022-05-20 23:26 UTC, hotbreakb commented on frontend/src/components/SearchCardItem/index.tsx
> +    border: 2px solid $#F8F8F8;
COLOR에서 가져와서 쓰는 걸로 수정 부탁드려요 ☺️

2022-05-20 23:26 UTC, hotbreakb commented on frontend/src/components/SearchCardList/index.tsx
> +      return <SearchCardItem key={summarizedSubscription.id} subscription={summarizedSubscription}></SearchCardItem>
`<SearchCardItem key={summarizedSubscription.id} subscription={summarizedSubscription}/>` 이렇게 하면 통일성이 더 좋을 거 같아요!

2022-05-20 23:26 UTC, hotbreakb commented on frontend/src/pages/Search/index.tsx
> +import SearchCardItem,{SearchCardItemProps} from '../../components/SearchCardItem';
`SearchCardItemProps`는 import할 필요가 없어보이네용

2022-05-21 07:32 UTC, tooooo1 requested changes
리뷰 남겼습니다!

2022-05-21 07:32 UTC, tooooo1 commented on frontend/src/pages/Search/index.tsx
> +    }
혹시 이거 무엇인가요? 제가 잘몰라서

2022-05-21 07:32 UTC, tooooo1 commented on frontend/src/components/SearchCardItem/index.tsx
> +    background-color: #FFFFFF;
PALETTE로 설정부탁드려요!

2022-05-21 07:32 UTC, tooooo1 commented on frontend/src/components/SearchCardItem/index.tsx
> +  margin: auto 0 0 auto;
0 auto인가요?

2022-05-21 07:34 UTC, jwun95 approved these changes
점점 리액트 어떻게 되어있는지 알거 같네요

2022-05-21 07:36 UTC, kmin-jeong commented on frontend/src/pages/Search/index.tsx
> +    }
이거 스페이스를 눌러야만 검색결과가 나와요!
searchlist는 검색 결과를 담은 컴포넌트이고 subdata는 검색 결과 데이터라고 보시면 되요!

2022-05-21 07:36 UTC, kmin-jeong commented on frontend/src/components/SearchCardItem/index.tsx
> +  margin: auto 0 0 auto;
margin left,right,bottom,top한꺼번에 줄려고 이렇게 쓴거에요!

2022-05-21 07:41 UTC, tooooo1 approved these changes

2022-05-21 09:18 UTC, hotbreakb commented on frontend/src/pages/Search/index.tsx
> +import SearchCardList, {SearchCardListProps} from '../../components/SearchCardList';
`SearchCardListProps`는 어디서 쓰나요?

2022-05-21 09:18 UTC, hotbreakb commented on frontend/src/types/index.ts
> +export type SummarizedSubscription = {
오~ 좋아요

2022-05-21 10:12 UTC, kmin-jeong commented on frontend/src/pages/Search/index.tsx
> +import SearchCardList, {SearchCardListProps} from '../../components/SearchCardList';
쓸일이 없어서 제거했습니다!

2022-05-21 10:14 UTC, Lela12 approved these changes
확인했습니다!!

2022-05-21 10:24 UTC, merged