Feat: type 수정
subscriptionRescueTeam/save-my-youth pull request #213
Opened 2022-05-23 09:26 UTC by kmin-jeong

### PR 타입(하나 이상의 PR 타입을 선택해주세요)

- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
ex) feat/167/sortbuttom -> dev

### 변경 사항

usePopular,uselatest 후크 수정
중복되는 타입 수정

### 테스트 결과
![캡5](https://user-images.githubusercontent.com/53456037/169788429-169ab7cc-a5c3-41d6-a5d6-56076fdf7ecc.jpg)

### Issue

2022-05-23 09:30 UTC, tooooo1 requested changes
고생하셨어요. 
그런데 프리티어 적용 안 되어 있어요. 확인 부탁드려요.

2022-05-23 09:50 UTC, Lela12 approved these changes
확인했습니다!

2022-05-23 09:54 UTC, hotbreakb reviewed
다음에는 commit 메시지에 `Fix: 내용` 이렇게 써주세요~!

2022-05-23 10:30 UTC, jwun95 approved these changes
수고하셨습니다.

2022-05-23 12:25 UTC, Lela12 approved these changes
확인했습니다!

2022-05-24 00:26 UTC, tooooo1 approved these changes

2022-05-24 00:26 UTC, merged